### ISSUE TITLE
Add `azure` and `rr` gems

### ISSUE THREAD

**Issue by sandstrom** [kddnewton/gemfilelint#64]
I got false positive warnings for these two, and they fairly popular both of them (azure not really maintained though).

https://rubygems.org/gems/rr/
https://rubygems.org/gems/azure/

**Comment by kddnewton** [comment]
I'd rather not add gems manually, as it's just based on download count. I would like to implement your idea of an override though, as described in #65.

**Comment by sandstrom** [comment]
Out of curiosity, what's the current threshold?

https://rubygems.org/gems/rr/ has 4.5 million downloads

**Comment by kddnewton** [comment]
It's 1000 (https://github.com/kddnewton/gemfilelint/blob/main/bin/load-pg-dump#L96). I could probably bump it by a bit I suppose, just haven't yet.

**Comment by sandstrom** [comment]
Alright, I understand that you need some type of cap.

https://rubygems.org/gems/secure_headers/ (which seems to be NO 1000 right now) has about 10M downloads. I'm guessing it's a pareto distribution so if you'd like to go down to, say, 5M downloads you'd probably have to add another 10K or so gems to the list.

I'm not in a position to know what a reasonable cutoff would be. But for tools like this, I think it's good to keep the number of false positives down.

**Comment by kddnewton** [comment]
I'm not sure how unreasonable it is to expect that a malicious gem could generate a couple million downloads in order to get onto this list. I'll do some investigation, might be oversecure at the moment.

**Comment by sandstrom** [comment]
Good question! 

Maybe there should also be a time-threshold, e.g. the gem should be at least 6 months old.
